### ISSUE TITLE
/docs dynamic and static route error 

### ISSUE THREAD

**Issue by Gitstar-OC** [Gitstar-OC/mindect#35]
**Describe the bug**
 ⚠ Failed to reload dynamic routes: Error: You cannot define a route with the same specificity as a optional catch-all route ("/docs" and "/docs[[...slug]]").
    at UrlNode._smoosh (C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\shared\lib\router\utils\sorted-routes.js:42:23)
    at C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\shared\lib\router\utils\sorted-routes.js:32:68
    at Array.map (<anonymous>)
    at UrlNode._smoosh (C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\shared\lib\router\utils\sorted-routes.js:32:38)
    at UrlNode.smoosh (C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\shared\lib\router\utils\sorted-routes.js:16:21)
    at getSortedRoutes (C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\shared\lib\router\utils\sorted-routes.js:167:17)
    at Watchpack.<anonymous> (C:\Users\chand\Mindect\mindect\node_modules\.pnpm\next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:558:65)

**To Reproduce**
N/A

**Expected behavior**
/docs should show the single file

**Comment by Gitstar-OC** [comment]
solved with this [https://github.com/Gitstar-OC/mindect/pull/36] request and commit
